Silk BLUD Gest/Models/Donors.cs
namespace Silk_BLUD_Gest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Runtime.CompilerServices;

    public partial class Donors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donors()
        {
            Donations = new HashSet<Donations>();
            Exams = new HashSet<Exams>();
            Stock = new HashSet<Stock>();
        }

        [Key]
        public int DonorID { get; set; }

        [Required]
        [StringLength(30)]
        [Display(Name = "Nome")]
        public string Name { get; set; }

        [Required]
        [StringLength(30)]
        [Display(Name = "Cognome")]
        public string Lastname { get; set; }

        [Required]
        [Display(Name = "Indirizzo")]
        public string Address { get; set; }

        [Required]
        [StringLength(30)]
        [Display(Name = "Telefono")]
        public string Contact { get; set; }

        [Display(Name = "Attiva")]
        public bool Active { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "Data parto")]
        public DateTime DeliveryDate { get; set; }

        [Display(Name = "Settimana di gestazione (al parto)")]
        public int GestationWeek { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "Data inizio donazione")]
        public DateTime? DonorSince { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "Data fine donazione")]
        public DateTime? DonorTo { get; set; }

        [Display(Name = "Dati Clinici")]
        public string ClinicalNotes { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "Tiralatte fornito in dotazione dal")]
        public DateTime? BreastPumpProvided { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "Al")]
        public DateTime? BreastPumpTaken { get; set; }

        [Display(Name = "Totale donato")]
        public double TotalDonated { get; set; }

        [NotMapped]
        public bool CollectionConfirmed { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donations> Donations { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exams> Exams { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<Stock> Stock { get; set; }
    }
}

Silk BLUD Gest/Controllers/DonationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Silk_BLUD_Gest.Models;

namespace Silk_BLUD_Gest.Controllers
{
    public class DonationsController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Donations
        public ActionResult Index()
        {
            var donations = db.Donations.Include(d => d.Donors);
            return View(donations.ToList());
        }

        // GET: Donations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donations donations = db.Donations.Find(id);
            if (donations == null)
            {
                return HttpNotFound();
            }
            return View(donations);
        }

        // GET: Donations/Create

        public ActionResult Create(string id)
        {
            if (id == null )
            {
                return RedirectToAction("Index","Donors");
            }


            ViewBag.DonorID = id;
            return View();
        }

        // POST: Donations/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DonationID,DonorID,FreezingDate,Quantity,BottleNum")] Donations donation)
        {
            if (ModelState.IsValid)
            {
                db.Donations.Add(donation);
                db.SaveChanges();

                Stock.AddToStock(donation, db);

                return RedirectToAction("Index","Donors");
            }

            ViewBag.DonorID = new SelectList(db.Donors, "DonorID", "Name", donation.DonorID);
            return View(donation);
        }

        // GET: Donations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donations donations = db.Donations.Find(id);
            if (donations == null)
            {
                return HttpNotFound();
            }
            ViewBag.DonorID = new SelectList(db.Donors, "DonorID", "Name", donations.DonorID);
            return View(donations);
        }

        // POST: Donations/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DonationID,DonorID,FreezingDate,Quantity,BottleNum")] Donations donations)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donations).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DonorID = new SelectList(db.Donors, "DonorID", "Name", donations.DonorID);
            return View(donations);
        }

        // GET: Donations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donations donations = db.Donations.Find(id);
            if (donations == null)
            {
                return HttpNotFound();
            }
            return View(donations);
        }

        // POST: Donations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Donations donations = db.Donations.Find(id);
            db.Donations.Remove(donations);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Silk BLUD Gest/Controllers/DonorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Silk_BLUD_Gest.Models;

namespace Silk_BLUD_Gest.Controllers
{
    public class DonorsController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Donors
        public ActionResult Index()
        {
            return View(db.Donors.ToList());
        }

        public ActionResult IndexActive()
        {
            return View(db.Donors.Where(d => d.Active));
        }

        [HttpPost]
        public ActionResult IndexActive(List<int> id)
        {
            return RedirectToAction("Index","Donors");
        }

        // COMPLETARE

        public ActionResult UpdateDonorState(string id)
        {
            if(id != null) {
                Donors current = db.Donors.Find(Convert.ToInt32(id));

                return View(current);
            }
            else
            {
                return RedirectToAction("Index","Donors");
            }
           
        }

        public ActionResult UpdateConfirmation(string id)
        {
            if(id != null) {
                try
                {
                    Donors current = db.Donors.Find(Convert.ToInt32(id));
                    current.Active = true;
                    current.DonorSince = DateTime.Now;
                    current.DonorTo = current.DonorSince.Value.AddYears(1);

                    db.Entry(current).State = EntityState.Modified;
                    db.SaveChanges();

                    ViewBag.StatusOkMsg = $"Attivazione donatrice {current.DonorID} avvenuta con successo";
                    
                    return RedirectToAction("Index","Donors");
                }
                catch (Exception ex)
                {
                    ViewBag.ErrMsg = ex.Message;
                    return View();
                }
            }
            else
            {
                return RedirectToAction("Index", "Donors");
            }
              
        }





        // GET: Donors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donors donors = db.Donors.Find(id);
            if (donors == null)
            {
                return HttpNotFound();
            }
            return View(donors);
        }

        // GET: Donors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Donors/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Donors donor)
        {
            
            if (ModelState.IsValid)
            {
                
                db.Donors.Add(donor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(donor);
        }

        // GET: Donors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donors donors = db.Donors.Find(id);
            if (donors == null)
            {
                return HttpNotFound();
            }
            return View(donors);
        }

        // POST: Donors/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DonorID,Name,Lastname,Address,Contact,Active,DeliveryDate,GestationWeek,DonorSince,DonorTo,ClinicalNotes,BreastPumpProvided,BreastPumpTaken,TotalDonated")] Donors donors)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donors).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(donors);
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Silk BLUD Gest/Views/Donors/Create.cshtml
@model Silk_BLUD_Gest.Models.Donors

@{
    ViewBag.Title = "Create";
}

<h2>Aggiungi Donatrice</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
        </div>
    </div>

    @* Al momento dell' inserimento, dovrebbe essere Attiva? *@

    @*<div class="form-group">
        @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Active)
                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>*@

    @*<div id="DonorDates">
        <div class="form-group">
            @Html.LabelFor(model => model.DonorSince, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonorSince, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.DonorSince, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonorTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonorTo, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.DonorTo, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.DeliveryDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DeliveryDate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.DeliveryDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GestationWeek, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GestationWeek, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GestationWeek, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.ClinicalNotes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ClinicalNotes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClinicalNotes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div>
        <span>Tiralatte fornito?</span>
        <input type="checkbox" id="BreastPumpBox" />
    </div>

    <div id="BreastPumpInputs">
        <div class="form-group">
            @Html.LabelFor(model => model.BreastPumpProvided, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BreastPumpProvided, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BreastPumpProvided, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BreastPumpTaken, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BreastPumpTaken, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BreastPumpTaken, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Aggiungi" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Torna Indietro", "Index")
</div>

<script type="text/javascript">
    $(document).ready(function () {
       /* $('#DonorDates').hide();*/
        $('#BreastPumpInputs').hide();

        //$('#Active').change(function () {
        //    $('#DonorDates').slideToggle(500);
        //})

        $('#BreastPumpBox').change(function () {
            
            $('#BreastPumpInputs').slideToggle(500);
        })
    })
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Silk BLUD Gest/Views/Donors/Details.cshtml
@model Silk_BLUD_Gest.Models.Donors

@{
    ViewBag.Title = "Details";
}



<div>
    <h3>Dettagli di @Model.Name @Model.Lastname</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GestationWeek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GestationWeek)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonorSince)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonorSince)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonorTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonorTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClinicalNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClinicalNotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BreastPumpProvided)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BreastPumpProvided)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BreastPumpTaken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BreastPumpTaken)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.TotalDonated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalDonated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifica", "Edit", new { id = Model.DonorID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Silk BLUD Gest/Views/Donors/Index.cshtml
@model IEnumerable<Silk_BLUD_Gest.Models.Donors>

@{
    ViewBag.Title = "Index";
}

<div class="d-flex justify-content-between mb-5">
    <h2 class="d-inline-block">Tutte le Donatrici</h2>

    <span class="ms-auto">
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-blud text-light" })
    </span>
</div>


<table class="table" style="max-width: 900px;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lastname)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Address)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Contact)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Active)
        </th>*@
        @*<th>
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </th>*@
        @*<th>
            @Html.DisplayNameFor(model => model.GestationWeek)
        </th>*@
        @*<th>
            @Html.DisplayNameFor(model => model.DonorSince)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DonorTo)
        </th>*@
        @*<th>
            @Html.DisplayNameFor(model => model.ClinicalNotes)
        </th>*@
        @*<th>
            @Html.DisplayNameFor(model => model.BreastPumpProvided)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BreastPumpTaken)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalDonated)
        </th>*@
        <th class="w-50">
        </th>
    </tr>

@foreach (var item in Model) {
    <tr style="height:4em;" class="donorTr">
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lastname)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Contact)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DeliveryDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GestationWeek)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DonorSince)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DonorTo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClinicalNotes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BreastPumpProvided)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BreastPumpTaken)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalDonated)
        </td>*@
        <td style="text-align: end;">
            <div class="linksInTd" hidden>
                @Html.ActionLink("Carica donazione", "Create", "Donations", new { id = item.DonorID }, new { @class="btn btn-primary"})
                @Html.ActionLink("Details", "Details", new { id = item.DonorID }, new { @class = "btn btn-primary" })
                @if (!item.Active)
                {
                   @Html.ActionLink("Attiva", "UpdateDonorState", new { id = item.DonorID }, new { @class = "btn btn-success" })
                }

            </div>
        </td>
    </tr>
}

</table>


<script>
    $(document).ready(function () {
        $('.donorTr').hover(function () {
            $(this).find('.linksInTd').removeAttr('hidden');
        }, 
            function () {
                $(this).find('.linksInTd').attr('hidden', '');

            }
        )
    })
</script>

Silk BLUD Gest/Views/Donors/IndexActive.cshtml
@model IEnumerable<Silk_BLUD_Gest.Models.Donors>

@{
    ViewBag.Title = "IndexActive";
}

<h2>Programmazione Raccolta</h2>


@using (Html.BeginForm())
{
    <h4>Donatrici Attive</h4>
    <table class="table w-75">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lastname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contact)
            </th>
            <th>Da raccogliere</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.DonorID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lastname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contact)
                </td>
                <td>
                    <input class="CollectionBtn btn btn-default ms-auto" value="add" type="button"/>
                </td>
            </tr>
        }

    </table>
    <input id="CollectionConfirm" type="button" value="Conferma" class="btn btn-primary" />
}

<ul id="Confirmed">

</ul>

<script type="text/javascript">
    //$(document).ready(function () {
    //    $(".CollectionBtn").click(function () {
    //        var row = $(this).closest("TR");
    //        var name = $("TD", row).eq(1).html();
    //        var id = $("TD", row).eq(0).html();

    //        /*console.log(name);*/
    //        $("#Confirmed").append("<li>"+ id +" - "+ name + "</li>");
    //    })

        

    //    $("#CollectionConfirm").click(function () {

    //    })
    //})
</script>

Silk BLUD Gest/Views/Donors/UpdateDonorState.cshtml
@model Silk_BLUD_Gest.Models.Donors

@{
    ViewBag.Title = "UpdateDonorState";
}

<h2>Attivazione Donatrice: @Model.DonorID</h2>
<p>@Model.Name @Model.Lastname</p>


   
    
    <div class="form-horizontal">
        <h4>Modificare lo stato della donatrice?</h4>
        <hr />
        


        <div>
            <div class="col-md-offset-2 col-md-10 d-flex gap-4">
                @*<a href="@Url.Action("UpdateConfirmation", "Donors")" value="Conferma" class="btn btn-primary"></a>*@
                <a href="@Url.Action("Index","Donors")" class="btn btn-primary" >Annulla</a>
                @Html.ActionLink("Conferma","UpdateConfirmation","Donors",new { id= Model.DonorID},new { @class= "btn btn-primary"})
            </div>
        </div>
    </div>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}